### ISSUE TITLE
Support lower android version

### ISSUE THREAD

**Issue by tellfa** [michelelacorte/SwipeableCard#1]
hi. please edit this project and support lower android version. for example api +14 . 
tnx

**Comment by michelelacorte** [comment]
Thanks for the tip @tellfa , trying API 15 and seems to be fine, the next version will be compatible 15+

**Comment by tellfa** [comment]
please api +14 . pleaseeeeeee

**Comment by michelelacorte** [comment]
I'm testing with 11+ @tellfa

**Comment by michelelacorte** [comment]
@tellfa I updated the library , I hope you have been helpful!

**Comment by tellfa** [comment]
i love you man <3
