### ISSUE TITLE
[PROBLEM][SOLVED] Cannot resolve .image() in RecyclerView OptionViews builder.

### ISSUE THREAD

**Issue by atiqueakbani** [michelelacorte/SwipeableCard#10]
The error code provided in your documentation:
`optionViews.add(new OptionView.Builder()
                .image(R.drawable.bus_stop)
                .title("TITLE")
                .colorTitle(R.color.colorPrimary)
                .menuItem(R.menu.menu_main)
                .toolbarListener(toolbarListener).build());
        `

The working code:
`
        optionViews.add(new OptionView.Builder()
                .normalCard()
                .image(R.drawable.bus_stop)
                .title("TITLE")
                .colorTitle(R.color.colorPrimary)
                .menuItem(R.menu.menu_main)
                .toolbarListener(toolbarListener).build());`

Please see that.

Regards

**Comment by michelelacorte** [comment]
In documantazione it is well written..

**Comment by atiqueakbani** [comment]
Sorry I have not come through that. Please provide me the link of that page where it is mentioned.

Thanks.

**Comment by michelelacorte** [comment]
This is for Single Card https://github.com/michelelacorte/SwipeableCard/blob/master/SINGLECARD.md
