### ISSUE TITLE
com.google.android.gms.maps.MapView not found

### ISSUE THREAD

**Issue by gruessung** [michelelacorte/SwipeableCard#12]
While compiling i getting this error:
`/home/alexander/StudioProjects/Ichleihedir/app/build/intermediates/exploded-aar/it.michelelacorte.swipeablecard/library/2.3.0/res/layout/maps_card_layout.xml
Error:(10) No resource identifier found for attribute 'liteMode' in package 'de.gvisions.oweapp'
Error:(10) No resource identifier found for attribute 'mapType' in package 'de.gvisions.oweapp'`

**Comment by michelelacorte** [comment]
Read this line:

```
Error:(10) No resource identifier found for attribute 'liteMode' in package 'de.gvisions.oweapp' 
Error:(10) No resource identifier found for attribute 'mapType' in package 'de.gvisions.oweapp'
```

This is not my library, it was generate from package de.gvisions.oweapp

**Comment by davidmarinangeli** [comment]
I've the same issue after adding your library. Solved deleting the two attributes.
