### ISSUE TITLE
About setting duration of the card animation showing.

### ISSUE THREAD

**Issue by saggy** [michelelacorte/SwipeableCard#2]
Hi, michele,

Thank your for your effort.
I have question for you , i am trying to increase the speed of the transition of card showing, i had tried to increase the duration of the card, but it will not effect.

you had mention the method to set the duration of card
setDuration(long duration);

i had increased the duration , but there is no change in duration it was as same as before.

please suggest me some thing.

**Comment by michelelacorte** [comment]
Thanks @saggy !!
Where are you calling setDuration() ?? because I can assure you that all methods work..

**Comment by saggy** [comment]
Thanxs @Michelelacorte

I have solved the issue, there was a small mistake done by me, by not assigning the variable global, so the duration is always passing as 0.

Thanx for the quick response.
