### ISSUE TITLE
I have some problems

### ISSUE THREAD

**Issue by kevinisbest** [michelelacorte/SwipeableCard#9]
i want to use RecyclerView
but it shows some errors
![image](https://cloud.githubusercontent.com/assets/10130649/13896676/321ff900-edd0-11e5-9a03-1a77adb9b754.png)

and this is the messages
![image](https://cloud.githubusercontent.com/assets/10130649/13896684/77e94784-edd0-11e5-9530-a0583d2f9fc0.png)
 
did i do something wrong??

**Comment by kevinisbest** [comment]
after adding `.normalCard()` my bugs solve
![image](https://cloud.githubusercontent.com/assets/10130649/13897130/c3344418-ede0-11e5-8227-9f86a5ab8421.png)

**Comment by michelelacorte** [comment]
Yes with `2.3.0` is necessary to select type of card, it is only if you compile with github project, because I haven't release that on bintray.
Thanks.
